#!/bin/bash

set -e
set -o pipefail

buildit ()
{
	MINHEAD=`/bin/curl -s \
		https://api.github.com/repos/defensec/dssp1-minimal/git/refs/heads/master \
			| /bin/grep "sha" | /bin/awk -F "\"" '{ print $4 }'`

	BASEHEAD=`/bin/curl -s \
		https://api.github.com/repos/defensec/dssp1-base/git/refs/heads/master \
			| /bin/grep "sha" | /bin/awk -F "\"" '{ print $4 }'`

	/bin/test -e ${HOME}/rpmbuild/SOURCES/dssp1-minimal-${DSSP1MINHEAD}.tar.gz \
		|| /bin/wget -q \
			https://github.com/defensec/dssp1-minimal/archive/${MINHEAD}/dssp1-minimal-${MINHEAD}.tar.gz \
				-O ${HOME}/rpmbuild/SOURCES/dssp1-minimal-${MINHEAD}.tar.gz

	/bin/test -e ${HOME}/rpmbuild/SOURCES/dssp1-base-${DSSP1BASEHEAD}.tar.gz \
		|| /bin/wget -q \
			https://github.com/defensec/dssp1-base/archive/${BASEHEAD}/dssp1-base-${BASEHEAD}.tar.gz \
				-O ${HOME}/rpmbuild/SOURCES/dssp1-base-${BASEHEAD}.tar.gz

	/bin/test -e ${HOME}/rpmbuild/SPECS/dssp1-minimal.spec \
		|| /bin/wget -q \
			https://raw.githubusercontent.com/defensec/dssp1-minimal/master/dssp1-minimal.spec \
				-O ${HOME}/rpmbuild/SPECS/dssp1-minimal.spec

	/bin/sed -i \
		"s/%global commit0.*/%global commit0 $MINHEAD/" \
			${HOME}/rpmbuild/SPECS/dssp1-minimal.spec

	/bin/sed -i \
		"s/%global commit1.*/%global commit1 $BASEHEAD/" \
			${HOME}/rpmbuild/SPECS/dssp1-minimal.spec

	/bin/rpmbuild -ba ${HOME}/rpmbuild/SPECS/dssp1-minimal.spec
}

devtree ()
{
	if ! /bin/test -d ${HOME}/rpmbuild
	then

		/bin/rpmdev-setuptree

		buildit

		/bin/mv ${HOME}/rpmbuild/{RPMS/noarch/,SRPMS}/dssp1-*.rpm \
			${HOME}/

		/bin/rm -rf ${HOME}/rpmbuild
	else

		buildit
	fi
}

if [[ $UID = 0 ]]
then
	if ! /bin/rpm -q rpmdevtools rpm-build policycoreutils wget sed curl
	then

		/bin/dnf -y --setopt=install_weak_deps=false install \
			rpmdevtools policycoreutils wget sed curl

		devtree

		/bin/dnf -y history undo last
	else

		devtree
	fi

elif ! [[ $UID = 0 ]]
then
	if ! /bin/sudo /bin/rpm -q rpmdevtools rpm-build policycoreutils wget sed curl
	then

		/bin/sudo /bin/dnf -y --setopt=install_weak_deps=false install \
			rpmdevtools policycoreutils wget sed curl

		devtree

		/bin/sudo /bin/dnf -y history undo last
	else

		devtree
	fi
fi

exit
#EOF
